version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "06:45"
    timezone: Asia/Dacca
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: Simplify.Xml.Sources
    versions:
    - 1.2.0
    - 1.2.1
    - 1.3.0
  - dependency-name: Simplify.System
    versions:
    - 1.5.0
    - 1.6.0
