name: Build Package

on: push

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            solution: Simplify.sln
            tests-exclude-category: Linux
          - os: ubuntu-latest
            solution: Simplify.NetCore.sln
            tests-exclude-category: Windows

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4.1.1

      - name: Install DotNet
        uses: actions/setup-dotnet@v4

      - name: Restore Dependencies
        run: dotnet restore ${{ matrix.solution }}

      - name: Build Packages
        run: dotnet build ${{ matrix.solution }} --no-restore -c Release

      - name: Perform Unit Testing
        run: dotnet test ${{ matrix.solution }} --no-build -c Release --filter "TestCategory != Integration & TestCategory != ${{ matrix.tests-exclude-category }}" --verbosity normal

      - name: Create Packages
        run: dotnet pack ${{ matrix.solution }} --no-build -c Release -o ./publish

      - name: Create Source Packages
        if: ${{ matrix.os == 'windows-latest' }}
        shell: pwsh
        working-directory: .
        run: ./MakeSourcePackages.ps1

      - name: Create packages artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Packages
          path: ./src/publish/
