name: Build Package

on: push

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            solution: Simplify.sln
          - os: buntu-latest
            solution: Simplify.Linux.sln

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install DotNet
        uses: actions/setup-dotnet@v1

      - name: Restore Dependencies
        run: dotnet restore ${{ matrix.solution }}

      - name: Build Packages
        run: dotnet build ${{ matrix.solution }} --no-restore -c Release

      - name: Perform Unit Testing
        run: dotnet test ${{ matrix.solution }} --no-build -c Release --filter TestCategory!=Integration --verbosity normal

      - name: Create Packages
        run: dotnet pack ${{ matrix.solution }} --no-build -c Release -o ./publish

      - name: Create Source Packages
        shell: pwsh
        working-directory: .
        run: ./MakeSourcePackages.ps1

      - name: Create packages artifact
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: ./src/publish/
